services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      EDITION: "core"
      VERSION: "11"
      USERNAME: "MASTER"
      PASSWORD: "admin@123"
      RAM_SIZE: "2G"     # Set RAM_SIZE to 3G
      CPU_CORES: "8"      # Set CPU_CORES to 16
      DISK_SIZE: "256G"
      DISK2_SIZE: "100G"
      MANUAL: "Y"
      LANGUAGE: "en-US"
      REGION: "en-US"
      KEYBOARD: "en-US"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m